spring:
  cloud:
    gateway:
      routes:
        - id: golden_route
          uri: https://httpbin.org
          predicates:
            - Path=/api/**
            - GoldenCustomer=true,customerId
          filters:
            - StripPrefix=1
            - AddRequestHeader=Golden-Customer,true
        - id: common_route
          uri: https://httpbin.org
          predicates:
            - Path=/api/**
            - name: GoldenCustomer
              args:
                golden: false
                customerIdCookie: customerId
          filters:
            - StripPrefix=1
            - AddRequestHeader=Golden-Customer,false